spring:
  application:
    name: sharding-test
  main:
    allow-bean-definition-overriding: true
#  profiles:
#    active: sharding-databases
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 150
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
#      jdbc-url: jdbc:mysql://10.201.62.180:3306/demo_ds_master?characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true&useInformationSchema=false
#      jdbc-url: jdbc:mysql://10.201.62.180:3306/demo_ds_master?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://10.200.20.94:30093/demo_ds_master?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: Link$2013
    dynamic:
      seata: true
  shardingsphere:
    enabled: true
    mode:
      type: Memory
    props:
      sql-show: true
    datasource:
      names: ds-0,ds-1,ds-2
      ds-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.200.20.94:30093/demo_ds?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
        username: root
        password: Link$2013
        maximum-pool-size: 150
        minimum-idle: 10
      ds-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.200.20.94:30093/demo_ds_1?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
        username: root
        password: Link$2013
        maximum-pool-size: 150
        minimum-idle: 10
      ds-2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.200.20.94:30093/demo_ds_2?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
        username: root
        password: Link$2013
        maximum-pool-size: 150
        minimum-idle: 10
    rules:
      sharding:
        default-database-strategy:
          standard:
            sharding-column: order_id
            sharding-algorithm-name: slotAlgorithm
        sharding-algorithms:
          slotAlgorithm:
            props:
              strategy: standard
              algorithmClassName: com.rlynic.sharding.slot.database.strategy.HashSlotShardingAlgorithm
            type: CLASS_BASED
        binding-tables: t_order,t_order_item
        tables:
          t_order:
#            tableStrategy:
#              standard:
#                shardingColumn: order_id
#                shardingAlgorithmName: slotAlgorithm
            actual-data-nodes: ds-$->{0..2}.t_order
            keyGenerateStrategy:
              column: order_id
              keyGeneratorName: snowflake
          t_order_item:
            actual-data-nodes: ds-$->{0..2}.t_order_item
#            tableStrategy:
#              standard:
#                shardingColumn: order_item_id
#                shardingAlgorithmName: slotAlgorithm
            keyGenerateStrategy:
              column: order_item_id
              keyGeneratorName: snowflake
        key-generators:
          snowflake:
            type: SNOWFLAKE

seata:
  enabled: false
  application-id: sharding-test
  tx-service-group: springboot-seata-group
  registry:
    type: file
  config:
    type: file
    file:
      name: file.conf
  service:
    grouplist:
      default: 10.200.21.76:28080
#      default: 10.201.62.180:8091
    vgroup-mapping:
      springboot-seata-group: default
  client:
    rm:
      report-success-enable: true
      table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
      report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
      async-commit-buffer-limit: 10000 # 异步提交缓存队列长度（默认10000）
      lock:
        retry-interval: 10 # 校验或占用全局锁重试间隔（默认10ms）
        retry-times: 30 # 校验或占用全局锁重试次数（默认30）
        retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
    tm:
      commit-retry-count: 5 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
      rollback-retry-count: 5  # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
      degrade-check-allow-times: 30
  enableAutoDataSourceProxy: true
  data-source-proxy-mode: AT

  transport:
    enable-client-batch-send-request: false
    thread-factory:
      worker-thread-size: 100

mybatis:
  config-location: classpath:META-INF/mybatis-config.xml
logging:
  level:
    root: debug
slot:
  sharding:
    range:
      datasource:
        ds-0: "{0, 5461}"
        ds-1: "{5462, 10921}"
        ds-2: "{10922, 16383}"
